version: '3'
services:
#Service sa toma el Dockerfile de ./openldap
 ldapserver:
  build: ./ldapserver
  hostname: ldapserver
  networks:
   ldap:
    ipv4_address: 10.121.158.100
 ldapclient:
  build: ./ldapclient
  hostname: ldapclient
  networks:
   ldap:
    ipv4_address: 10.121.158.101

networks:
  ldap:
    driver: bridge
    ipam:
     config:
       - subnet: 10.121.158.0/24
